network:
  openunison_host: "ou.apps.{{ hostvars[inventory_hostname]['inventory_hostname'] }}.nip.io"
  dashboard_host: "k8sdb.apps.{{ hostvars[inventory_hostname]['inventory_hostname'] }}.nip.io"
  api_server_host: ""
  session_inactivity_timeout_seconds: 900
  k8s_url: https://{{ hostvars[inventory_hostname]['inventory_hostname'] }}:6443
  

cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"

image: "docker.io/tremolosecurity/openunison-k8s-activedirectory:latest"
amq_image: "docker.io/tremolosecurity/activemq-docker:latest"
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: kubernetes
enable_impersonation: false

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
certs:
  use_k8s_cm: false

#trusted_certs: []

trusted_certs:
  - name: ldaps
    pem_b64: {{ AD_LDAPS_CERT_B64 }}

active_directory:
  base: {{ AD_BASE_DN }}
  host: "{{ AD_HOST }}"
  port: "636"
  bind_dn: "{{ AD_BIND_DN }}"
  con_type: ldaps
  srv_dns: "false"

database:
  hibernate_dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  quartz_dialect: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://mariadb.mariadb.svc:3306/unison
  user: unison
  validation: SELECT 1

smtp:
  host: blackhole.blackhole.svc.cluster.local
  port: 25
  user: donotreply@domain.com
  from: donotreply@domain.com
  tls: false

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s