---
apiVersion: v1
kind: Namespace
metadata:
  name: smtp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smtp
  name: smtp
  namespace: smtp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: smtp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: smtp
    spec:
      containers:
      - env: []
        image: namshi/smtp
        imagePullPolicy: Always
        name: smtp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: smtp
  name: smtp
  namespace: smtp
spec:
  ports:
  - port: 25
    protocol: TCP
    targetPort: 25
  selector:
    app: smtp
  sessionAffinity: None
  type: ClusterIP